### ISSUE TITLE
watch.js not working on windows node v20.12.2

### ISSUE THREAD

**Issue by Dj-Viking** [tsoding/raycasting#2]
using windows 10 and just a PowerShell as my shell terminal;

```shell
npm run watch 

> raycasting@1.0.0 watch
> node watch.js

CMD: tsc [ '-w' ]
CMD: http-server [ '-p', '6969', '-a', '127.0.0.1', '-s' ]
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: spawn tsc ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn tsc',
  path: 'tsc',
  spawnargs: [ '-w' ]
}

Node.js v20.12.2
```

**Comment by Dj-Viking** [comment]
maybe this has something to do with it?

https://nodejs.org/en/blog/release/v20.12.2#notable-changes

**Comment by Dj-Viking** [comment]
Actually yeah node on this version while in windows you have to pass { shell: true } as spawnOptions to calling spawn

```javascript
/**
 * 
 * @returns {boolean}
 */
function isWindows() {
    return require("os").platform() === "win32";
}

/**
 * @type {Parameters<typeof spawn>[2]}
 */
const spawnOptions = isWindows() ? { "shell": true } : {};

/**
 * 
 * @param {string} program 
 * @param {string[]} args 
 * @returns {ReturnType<typeof spawn>}
 */
function cmd(program, args) {
    console.log('CMD:', program, args.flat(), spawnOptions);
```

**Comment by Dj-Viking** [comment]
```shell
npm run watch

> raycasting@1.0.0 watch
> node watch.js
2:13:10 PM - Starting compilation in watch mode...


2:13:10 PM - Found 0 errors. Watching for file changes.
(node:16848) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Dj-Viking** [comment]
because the thing is if node is < v20 the spawn will work with `tsc.cmd` but not `tsc`... > v20 `tsc.cmd` will not work you'll get EINVAL

```shell
CMD: tsc.cmd [ '-w' ]
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
    ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at cmd (C:\Users\ander\projects\raycasting\watch.js:5:15)
    at Object.<anonymous> (C:\Users\ander\projects\raycasting\watch.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v20.12.2
```
